#!/bin/sh

COLLECTION=${1:-jeru,tlv}

for letter in alef beys gimel daled hey vov zayin \
			  khes tes yud khaf lamed mem nun samekh \
			  ayin pey tzadi kuf reysh shin tof; do
	python `dirname $0`/csv2html.py -c $COLLECTION $letter.csv
done
	
