#!/bin/sh

for coll in jeru,tlv jeru tlv; do
    if [ ! -e $coll ] ; then
        mkdir  $coll
    fi
    cp yycat.css $coll/.
    for letter in alef beys gimel daled hey vov zayin \
    	khes tes yud khaf lamed mem nun samekh \
	ayin pey tzadi kuf reysh shin tof; do
	python `dirname $0`/csv2html.py -c $coll < $letter.csv > $coll/$letter.htm
    done
done
	
